/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VergleichRouteImport } from './routes/vergleich'
import { Route as BeratungRouteImport } from './routes/beratung'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPolicenRouteImport } from './routes/_authenticated.policen'
import { Route as AuthenticatedPoliceUploadRouteImport } from './routes/_authenticated.police-upload'
import { Route as AuthenticatedKuendigungRouteImport } from './routes/_authenticated.kuendigung'
import { Route as AuthenticatedFamilieOptimierenRouteImport } from './routes/_authenticated.familie-optimieren'
import { Route as AuthenticatedFamilieRouteImport } from './routes/_authenticated.familie'
import { Route as AuthenticatedEmpfehlungenRouteImport } from './routes/_authenticated.empfehlungen'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCheckRouteImport } from './routes/_authenticated.check'
import { Route as AuthenticatedPoliceBestaetigenPolicyIdRouteImport } from './routes/_authenticated.police-bestaetigen.$policyId'

const VergleichRoute = VergleichRouteImport.update({
  id: '/vergleich',
  path: '/vergleich',
  getParentRoute: () => rootRouteImport,
} as any)
const BeratungRoute = BeratungRouteImport.update({
  id: '/beratung',
  path: '/beratung',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPolicenRoute = AuthenticatedPolicenRouteImport.update({
  id: '/policen',
  path: '/policen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoliceUploadRoute =
  AuthenticatedPoliceUploadRouteImport.update({
    id: '/police-upload',
    path: '/police-upload',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKuendigungRoute = AuthenticatedKuendigungRouteImport.update({
  id: '/kuendigung',
  path: '/kuendigung',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilieOptimierenRoute =
  AuthenticatedFamilieOptimierenRouteImport.update({
    id: '/familie-optimieren',
    path: '/familie-optimieren',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilieRoute = AuthenticatedFamilieRouteImport.update({
  id: '/familie',
  path: '/familie',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpfehlungenRoute =
  AuthenticatedEmpfehlungenRouteImport.update({
    id: '/empfehlungen',
    path: '/empfehlungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckRoute = AuthenticatedCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoliceBestaetigenPolicyIdRoute =
  AuthenticatedPoliceBestaetigenPolicyIdRouteImport.update({
    id: '/police-bestaetigen/$policyId',
    path: '/police-bestaetigen/$policyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beratung': typeof BeratungRoute
  '/vergleich': typeof VergleichRoute
  '/check': typeof AuthenticatedCheckRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empfehlungen': typeof AuthenticatedEmpfehlungenRoute
  '/familie': typeof AuthenticatedFamilieRoute
  '/familie-optimieren': typeof AuthenticatedFamilieOptimierenRoute
  '/kuendigung': typeof AuthenticatedKuendigungRoute
  '/police-upload': typeof AuthenticatedPoliceUploadRoute
  '/policen': typeof AuthenticatedPolicenRoute
  '/police-bestaetigen/$policyId': typeof AuthenticatedPoliceBestaetigenPolicyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beratung': typeof BeratungRoute
  '/vergleich': typeof VergleichRoute
  '/check': typeof AuthenticatedCheckRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empfehlungen': typeof AuthenticatedEmpfehlungenRoute
  '/familie': typeof AuthenticatedFamilieRoute
  '/familie-optimieren': typeof AuthenticatedFamilieOptimierenRoute
  '/kuendigung': typeof AuthenticatedKuendigungRoute
  '/police-upload': typeof AuthenticatedPoliceUploadRoute
  '/policen': typeof AuthenticatedPolicenRoute
  '/police-bestaetigen/$policyId': typeof AuthenticatedPoliceBestaetigenPolicyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/beratung': typeof BeratungRoute
  '/vergleich': typeof VergleichRoute
  '/_authenticated/check': typeof AuthenticatedCheckRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empfehlungen': typeof AuthenticatedEmpfehlungenRoute
  '/_authenticated/familie': typeof AuthenticatedFamilieRoute
  '/_authenticated/familie-optimieren': typeof AuthenticatedFamilieOptimierenRoute
  '/_authenticated/kuendigung': typeof AuthenticatedKuendigungRoute
  '/_authenticated/police-upload': typeof AuthenticatedPoliceUploadRoute
  '/_authenticated/policen': typeof AuthenticatedPolicenRoute
  '/_authenticated/police-bestaetigen/$policyId': typeof AuthenticatedPoliceBestaetigenPolicyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/beratung'
    | '/vergleich'
    | '/check'
    | '/dashboard'
    | '/empfehlungen'
    | '/familie'
    | '/familie-optimieren'
    | '/kuendigung'
    | '/police-upload'
    | '/policen'
    | '/police-bestaetigen/$policyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/beratung'
    | '/vergleich'
    | '/check'
    | '/dashboard'
    | '/empfehlungen'
    | '/familie'
    | '/familie-optimieren'
    | '/kuendigung'
    | '/police-upload'
    | '/policen'
    | '/police-bestaetigen/$policyId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/beratung'
    | '/vergleich'
    | '/_authenticated/check'
    | '/_authenticated/dashboard'
    | '/_authenticated/empfehlungen'
    | '/_authenticated/familie'
    | '/_authenticated/familie-optimieren'
    | '/_authenticated/kuendigung'
    | '/_authenticated/police-upload'
    | '/_authenticated/policen'
    | '/_authenticated/police-bestaetigen/$policyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BeratungRoute: typeof BeratungRoute
  VergleichRoute: typeof VergleichRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vergleich': {
      id: '/vergleich'
      path: '/vergleich'
      fullPath: '/vergleich'
      preLoaderRoute: typeof VergleichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beratung': {
      id: '/beratung'
      path: '/beratung'
      fullPath: '/beratung'
      preLoaderRoute: typeof BeratungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/policen': {
      id: '/_authenticated/policen'
      path: '/policen'
      fullPath: '/policen'
      preLoaderRoute: typeof AuthenticatedPolicenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/police-upload': {
      id: '/_authenticated/police-upload'
      path: '/police-upload'
      fullPath: '/police-upload'
      preLoaderRoute: typeof AuthenticatedPoliceUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kuendigung': {
      id: '/_authenticated/kuendigung'
      path: '/kuendigung'
      fullPath: '/kuendigung'
      preLoaderRoute: typeof AuthenticatedKuendigungRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/familie-optimieren': {
      id: '/_authenticated/familie-optimieren'
      path: '/familie-optimieren'
      fullPath: '/familie-optimieren'
      preLoaderRoute: typeof AuthenticatedFamilieOptimierenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/familie': {
      id: '/_authenticated/familie'
      path: '/familie'
      fullPath: '/familie'
      preLoaderRoute: typeof AuthenticatedFamilieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empfehlungen': {
      id: '/_authenticated/empfehlungen'
      path: '/empfehlungen'
      fullPath: '/empfehlungen'
      preLoaderRoute: typeof AuthenticatedEmpfehlungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check': {
      id: '/_authenticated/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof AuthenticatedCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/police-bestaetigen/$policyId': {
      id: '/_authenticated/police-bestaetigen/$policyId'
      path: '/police-bestaetigen/$policyId'
      fullPath: '/police-bestaetigen/$policyId'
      preLoaderRoute: typeof AuthenticatedPoliceBestaetigenPolicyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckRoute: typeof AuthenticatedCheckRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpfehlungenRoute: typeof AuthenticatedEmpfehlungenRoute
  AuthenticatedFamilieRoute: typeof AuthenticatedFamilieRoute
  AuthenticatedFamilieOptimierenRoute: typeof AuthenticatedFamilieOptimierenRoute
  AuthenticatedKuendigungRoute: typeof AuthenticatedKuendigungRoute
  AuthenticatedPoliceUploadRoute: typeof AuthenticatedPoliceUploadRoute
  AuthenticatedPolicenRoute: typeof AuthenticatedPolicenRoute
  AuthenticatedPoliceBestaetigenPolicyIdRoute: typeof AuthenticatedPoliceBestaetigenPolicyIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckRoute: AuthenticatedCheckRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpfehlungenRoute: AuthenticatedEmpfehlungenRoute,
  AuthenticatedFamilieRoute: AuthenticatedFamilieRoute,
  AuthenticatedFamilieOptimierenRoute: AuthenticatedFamilieOptimierenRoute,
  AuthenticatedKuendigungRoute: AuthenticatedKuendigungRoute,
  AuthenticatedPoliceUploadRoute: AuthenticatedPoliceUploadRoute,
  AuthenticatedPolicenRoute: AuthenticatedPolicenRoute,
  AuthenticatedPoliceBestaetigenPolicyIdRoute:
    AuthenticatedPoliceBestaetigenPolicyIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BeratungRoute: BeratungRoute,
  VergleichRoute: VergleichRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
