/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VergleichRouteImport } from './routes/vergleich'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as BeratungRouteImport } from './routes/beratung'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppPolicenRouteImport } from './routes/_authenticated.app.policen'
import { Route as AuthenticatedAppPoliceUploadRouteImport } from './routes/_authenticated.app.police-upload'
import { Route as AuthenticatedAppKuendigungRouteImport } from './routes/_authenticated.app.kuendigung'
import { Route as AuthenticatedAppFamilieOptimierenRouteImport } from './routes/_authenticated.app.familie-optimieren'
import { Route as AuthenticatedAppFamilieRouteImport } from './routes/_authenticated.app.familie'
import { Route as AuthenticatedAppEmpfehlungenRouteImport } from './routes/_authenticated.app.empfehlungen'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated.app.dashboard'
import { Route as AuthenticatedAppCheckRouteImport } from './routes/_authenticated.app.check'
import { Route as ApiPublicHooksCleanupOrphanUploadsRouteImport } from './routes/api/public/hooks/cleanup-orphan-uploads'
import { Route as AuthenticatedAppPolicenPolicyIdRouteImport } from './routes/_authenticated.app.policen_.$policyId'
import { Route as AuthenticatedAppPoliceBestaetigenPolicyIdRouteImport } from './routes/_authenticated.app.police-bestaetigen.$policyId'

const VergleichRoute = VergleichRouteImport.update({
  id: '/vergleich',
  path: '/vergleich',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const BeratungRoute = BeratungRouteImport.update({
  id: '/beratung',
  path: '/beratung',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPolicenRoute = AuthenticatedAppPolicenRouteImport.update({
  id: '/app/policen',
  path: '/app/policen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPoliceUploadRoute =
  AuthenticatedAppPoliceUploadRouteImport.update({
    id: '/app/police-upload',
    path: '/app/police-upload',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppKuendigungRoute =
  AuthenticatedAppKuendigungRouteImport.update({
    id: '/app/kuendigung',
    path: '/app/kuendigung',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFamilieOptimierenRoute =
  AuthenticatedAppFamilieOptimierenRouteImport.update({
    id: '/app/familie-optimieren',
    path: '/app/familie-optimieren',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFamilieRoute = AuthenticatedAppFamilieRouteImport.update({
  id: '/app/familie',
  path: '/app/familie',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppEmpfehlungenRoute =
  AuthenticatedAppEmpfehlungenRouteImport.update({
    id: '/app/empfehlungen',
    path: '/app/empfehlungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/app/dashboard',
    path: '/app/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCheckRoute = AuthenticatedAppCheckRouteImport.update({
  id: '/app/check',
  path: '/app/check',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksCleanupOrphanUploadsRoute =
  ApiPublicHooksCleanupOrphanUploadsRouteImport.update({
    id: '/api/public/hooks/cleanup-orphan-uploads',
    path: '/api/public/hooks/cleanup-orphan-uploads',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppPolicenPolicyIdRoute =
  AuthenticatedAppPolicenPolicyIdRouteImport.update({
    id: '/app/policen_/$policyId',
    path: '/app/policen/$policyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPoliceBestaetigenPolicyIdRoute =
  AuthenticatedAppPoliceBestaetigenPolicyIdRouteImport.update({
    id: '/app/police-bestaetigen/$policyId',
    path: '/app/police-bestaetigen/$policyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beratung': typeof BeratungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/vergleich': typeof VergleichRoute
  '/app/check': typeof AuthenticatedAppCheckRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/empfehlungen': typeof AuthenticatedAppEmpfehlungenRoute
  '/app/familie': typeof AuthenticatedAppFamilieRoute
  '/app/familie-optimieren': typeof AuthenticatedAppFamilieOptimierenRoute
  '/app/kuendigung': typeof AuthenticatedAppKuendigungRoute
  '/app/police-upload': typeof AuthenticatedAppPoliceUploadRoute
  '/app/policen': typeof AuthenticatedAppPolicenRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/police-bestaetigen/$policyId': typeof AuthenticatedAppPoliceBestaetigenPolicyIdRoute
  '/app/policen/$policyId': typeof AuthenticatedAppPolicenPolicyIdRoute
  '/api/public/hooks/cleanup-orphan-uploads': typeof ApiPublicHooksCleanupOrphanUploadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beratung': typeof BeratungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/vergleich': typeof VergleichRoute
  '/app/check': typeof AuthenticatedAppCheckRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/empfehlungen': typeof AuthenticatedAppEmpfehlungenRoute
  '/app/familie': typeof AuthenticatedAppFamilieRoute
  '/app/familie-optimieren': typeof AuthenticatedAppFamilieOptimierenRoute
  '/app/kuendigung': typeof AuthenticatedAppKuendigungRoute
  '/app/police-upload': typeof AuthenticatedAppPoliceUploadRoute
  '/app/policen': typeof AuthenticatedAppPolicenRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/police-bestaetigen/$policyId': typeof AuthenticatedAppPoliceBestaetigenPolicyIdRoute
  '/app/policen/$policyId': typeof AuthenticatedAppPolicenPolicyIdRoute
  '/api/public/hooks/cleanup-orphan-uploads': typeof ApiPublicHooksCleanupOrphanUploadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/beratung': typeof BeratungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/vergleich': typeof VergleichRoute
  '/_authenticated/app/check': typeof AuthenticatedAppCheckRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/empfehlungen': typeof AuthenticatedAppEmpfehlungenRoute
  '/_authenticated/app/familie': typeof AuthenticatedAppFamilieRoute
  '/_authenticated/app/familie-optimieren': typeof AuthenticatedAppFamilieOptimierenRoute
  '/_authenticated/app/kuendigung': typeof AuthenticatedAppKuendigungRoute
  '/_authenticated/app/police-upload': typeof AuthenticatedAppPoliceUploadRoute
  '/_authenticated/app/policen': typeof AuthenticatedAppPolicenRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/police-bestaetigen/$policyId': typeof AuthenticatedAppPoliceBestaetigenPolicyIdRoute
  '/_authenticated/app/policen_/$policyId': typeof AuthenticatedAppPolicenPolicyIdRoute
  '/api/public/hooks/cleanup-orphan-uploads': typeof ApiPublicHooksCleanupOrphanUploadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/beratung'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/preise'
    | '/ueber-uns'
    | '/vergleich'
    | '/app/check'
    | '/app/dashboard'
    | '/app/empfehlungen'
    | '/app/familie'
    | '/app/familie-optimieren'
    | '/app/kuendigung'
    | '/app/police-upload'
    | '/app/policen'
    | '/app/'
    | '/app/police-bestaetigen/$policyId'
    | '/app/policen/$policyId'
    | '/api/public/hooks/cleanup-orphan-uploads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/beratung'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/preise'
    | '/ueber-uns'
    | '/vergleich'
    | '/app/check'
    | '/app/dashboard'
    | '/app/empfehlungen'
    | '/app/familie'
    | '/app/familie-optimieren'
    | '/app/kuendigung'
    | '/app/police-upload'
    | '/app/policen'
    | '/app'
    | '/app/police-bestaetigen/$policyId'
    | '/app/policen/$policyId'
    | '/api/public/hooks/cleanup-orphan-uploads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/beratung'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/preise'
    | '/ueber-uns'
    | '/vergleich'
    | '/_authenticated/app/check'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/empfehlungen'
    | '/_authenticated/app/familie'
    | '/_authenticated/app/familie-optimieren'
    | '/_authenticated/app/kuendigung'
    | '/_authenticated/app/police-upload'
    | '/_authenticated/app/policen'
    | '/_authenticated/app/'
    | '/_authenticated/app/police-bestaetigen/$policyId'
    | '/_authenticated/app/policen_/$policyId'
    | '/api/public/hooks/cleanup-orphan-uploads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BeratungRoute: typeof BeratungRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  PreiseRoute: typeof PreiseRoute
  UeberUnsRoute: typeof UeberUnsRoute
  VergleichRoute: typeof VergleichRoute
  ApiPublicHooksCleanupOrphanUploadsRoute: typeof ApiPublicHooksCleanupOrphanUploadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vergleich': {
      id: '/vergleich'
      path: '/vergleich'
      fullPath: '/vergleich'
      preLoaderRoute: typeof VergleichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beratung': {
      id: '/beratung'
      path: '/beratung'
      fullPath: '/beratung'
      preLoaderRoute: typeof BeratungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/policen': {
      id: '/_authenticated/app/policen'
      path: '/app/policen'
      fullPath: '/app/policen'
      preLoaderRoute: typeof AuthenticatedAppPolicenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/police-upload': {
      id: '/_authenticated/app/police-upload'
      path: '/app/police-upload'
      fullPath: '/app/police-upload'
      preLoaderRoute: typeof AuthenticatedAppPoliceUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/kuendigung': {
      id: '/_authenticated/app/kuendigung'
      path: '/app/kuendigung'
      fullPath: '/app/kuendigung'
      preLoaderRoute: typeof AuthenticatedAppKuendigungRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/familie-optimieren': {
      id: '/_authenticated/app/familie-optimieren'
      path: '/app/familie-optimieren'
      fullPath: '/app/familie-optimieren'
      preLoaderRoute: typeof AuthenticatedAppFamilieOptimierenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/familie': {
      id: '/_authenticated/app/familie'
      path: '/app/familie'
      fullPath: '/app/familie'
      preLoaderRoute: typeof AuthenticatedAppFamilieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/empfehlungen': {
      id: '/_authenticated/app/empfehlungen'
      path: '/app/empfehlungen'
      fullPath: '/app/empfehlungen'
      preLoaderRoute: typeof AuthenticatedAppEmpfehlungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/check': {
      id: '/_authenticated/app/check'
      path: '/app/check'
      fullPath: '/app/check'
      preLoaderRoute: typeof AuthenticatedAppCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/cleanup-orphan-uploads': {
      id: '/api/public/hooks/cleanup-orphan-uploads'
      path: '/api/public/hooks/cleanup-orphan-uploads'
      fullPath: '/api/public/hooks/cleanup-orphan-uploads'
      preLoaderRoute: typeof ApiPublicHooksCleanupOrphanUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/policen_/$policyId': {
      id: '/_authenticated/app/policen_/$policyId'
      path: '/app/policen/$policyId'
      fullPath: '/app/policen/$policyId'
      preLoaderRoute: typeof AuthenticatedAppPolicenPolicyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/police-bestaetigen/$policyId': {
      id: '/_authenticated/app/police-bestaetigen/$policyId'
      path: '/app/police-bestaetigen/$policyId'
      fullPath: '/app/police-bestaetigen/$policyId'
      preLoaderRoute: typeof AuthenticatedAppPoliceBestaetigenPolicyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppCheckRoute: typeof AuthenticatedAppCheckRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppEmpfehlungenRoute: typeof AuthenticatedAppEmpfehlungenRoute
  AuthenticatedAppFamilieRoute: typeof AuthenticatedAppFamilieRoute
  AuthenticatedAppFamilieOptimierenRoute: typeof AuthenticatedAppFamilieOptimierenRoute
  AuthenticatedAppKuendigungRoute: typeof AuthenticatedAppKuendigungRoute
  AuthenticatedAppPoliceUploadRoute: typeof AuthenticatedAppPoliceUploadRoute
  AuthenticatedAppPolicenRoute: typeof AuthenticatedAppPolicenRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppPoliceBestaetigenPolicyIdRoute: typeof AuthenticatedAppPoliceBestaetigenPolicyIdRoute
  AuthenticatedAppPolicenPolicyIdRoute: typeof AuthenticatedAppPolicenPolicyIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppCheckRoute: AuthenticatedAppCheckRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppEmpfehlungenRoute: AuthenticatedAppEmpfehlungenRoute,
  AuthenticatedAppFamilieRoute: AuthenticatedAppFamilieRoute,
  AuthenticatedAppFamilieOptimierenRoute:
    AuthenticatedAppFamilieOptimierenRoute,
  AuthenticatedAppKuendigungRoute: AuthenticatedAppKuendigungRoute,
  AuthenticatedAppPoliceUploadRoute: AuthenticatedAppPoliceUploadRoute,
  AuthenticatedAppPolicenRoute: AuthenticatedAppPolicenRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppPoliceBestaetigenPolicyIdRoute:
    AuthenticatedAppPoliceBestaetigenPolicyIdRoute,
  AuthenticatedAppPolicenPolicyIdRoute: AuthenticatedAppPolicenPolicyIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BeratungRoute: BeratungRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  PreiseRoute: PreiseRoute,
  UeberUnsRoute: UeberUnsRoute,
  VergleichRoute: VergleichRoute,
  ApiPublicHooksCleanupOrphanUploadsRoute:
    ApiPublicHooksCleanupOrphanUploadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
